### ISSUE TITLE
Will this be restored?

### ISSUE THREAD

**Issue by ectotoplogist** [SalesforceLabs/ifttt_salesforce#2]
The connector has been taken down from Heroku for quite some time, IFTTT has done wonders to my Salesforce instance, facilitating lead entry and internal communication. I hope that the app will be back online again.

**Comment by jamesward** [comment]
cc @jimjag

**Comment by ectotoplogist** [comment]
Hi there. Any updates to get the connector back online?

**Comment by jimjag** [comment]
There are no plans currently to re-enable the service.

**Comment by jamesward** [comment]
Note that someone could take the source in this repo and get this service running again.  I'd be happy to help set that up if someone wants to own the service.

**Comment by ectotoplogist** [comment]
At the very least, you should have the decency to close this as "won't fix", not "completed". Then again, it's Salesforce, so bromides is expected.
I've whipped up some FastAPI for internal use already, but thanks for your offer.
